name: Auto Scrape Movies
on:
  schedule:
    - cron: '0 */6 * * *' # تشغيل تلقائي كل 6 ساعات
  workflow_dispatch:      # يسمح لك بتشغيله يدوياً متى شئت

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Run Scraper Script
        run: php scraper.php

      - name: Commit and Push changes
        run: |
          git config --global user.name 'nexmex818-coder'
          git config --global user.email 'nexmex818-coder@users.noreply.github.com'
          git add movies.json
          git commit -m "Update movies.json [Skip CI]" || echo "No changes to commit"
          git push
